CARDS_LIST = [
    {"name": "Всадник на кабане", "elixir": 4, "image_url": "/static/cards/Hog.webp"},
    {"name": "П.Е.К.К.А", "elixir": 7, "image_url": "/static/cards/PEKKA.webp"},
    {"name": "Гигант", "elixir": 5, "image_url": "/static/cards/Giant.webp"},
    {"name": "Три мушкетёра", "image_url": "/static/cards/3M.webp"},
    {"name": "Королева лучниц", "image_url": "/static/cards/ArcherQueen.webp"},
    {"name": "Лучницы", "image_url": "/static/cards/Archers.webp"},
    {"name": "Дракончик", "image_url": "/static/cards/BabyD.webp"},
    {"name": "Шар", "image_url": "/static/cards/Balloon.webp"},
    {"name": "Бандитка", "image_url": "/static/cards/Bandit.webp"},
    {"name": "Варварская бочка", "image_url": "/static/cards/BarbBarrel.webp"},
    {"name": "Хижина Варваров", "image_url": "/static/cards/BarbHut.webp"},
    {"name": "Варвары", "image_url": "/static/cards/Barbs.webp"},
    {"name": "Гоблинская бочка", "image_url": "/static/cards/Barrel.webp"},
    {"name": "Летучие мыши", "image_url": "/static/cards/Bats.webp"},
    {"name": "Целмиельница", "image_url": "/static/cards/BattleHealer.webp"},
    {"name": "Берсеркша", "image_url": "/static/cards/Berserker.webp"},
    {"name": "Подрывник", "image_url": "/static/cards/Bomber.webp"},
    {"name": "Башня бомбёжка", "image_url": "/static/cards/BombTower.webp"},
    {"name": "Главная бандитка", "image_url": "/static/cards/BossBandit.webp"},
    {"name": "Вышибала", "image_url": "/static/cards/Bowler.webp"},
    {"name": "Пушка", "image_url": "/static/cards/Cannon.webp"},
    {"name": "Повозка с пушкой", "image_url": "/static/cards/CannonCart.webp"},
    {"name": "Клон", "image_url": "/static/cards/Clone.webp"},
    {"name": "Темный принц", "image_url": "/static/cards/DarkPrince.webp"},
    {"name": "Гоблин с лротиками", "image_url": "/static/cards/DartGob.webp"},
    {"name": "Землетрясение", "image_url": "/static/cards/Earthquake.webp"},
    {"name": "Элитные варвары", "image_url": "/static/cards/eBarbs.webp"},
    {"name": "Электродракон", "image_url": "/static/cards/eDragon.webp"},
    {"name": "Электрогигант", "image_url": "/static/cards/ElectroGiant.webp"},
    {"name": "Электрический дух", "image_url": "/static/cards/ElectroSpirit.webp"},
    {"name": "Эликсирный голем", "image_url": "/static/cards/ElixirGolem.webp"},
    {"name": "Громовержец", "image_url": "/static/cards/eWiz.webp"},
    {"name": "Палач", "image_url": "/static/cards/Exe.webp"},
    {"name": "Огненный шар", "image_url": "/static/cards/Fireball.webp"},
    {"name": "Огненная лучница", "image_url": "/static/cards/Firecracker.webp"},
    {"name": "Огненный дух", "image_url": "/static/cards/FireSpirit.webp"},
    {"name": "Рыбак", "image_url": "/static/cards/Fisherman.webp"},
    {"name": "Летучка", "image_url": "/static/cards/FlyingMachine.webp"},
    {"name": "Заморозка", "image_url": "/static/cards/Freeze.webp"},
    {"name": "Печь", "image_url": "/static/cards/Furnace.webp"},
    {"name": "Королевский призрак", "image_url": "/static/cards/Ghost.webp"},
    {"name": "Гигантский скелет", "image_url": "/static/cards/GiantSkelly.webp"},
    {"name": "Банда гоблинов", "image_url": "/static/cards/GobGang.webp"},
    {"name": "Гоблин-гигант", "image_url": "/static/cards/GobGiant.webp"},
    {"name": "Хижина гоблинов", "image_url": "/static/cards/GobHut.webp"},
    {"name": "Клетка с гоблином", "image_url": "/static/cards/GoblinCage.webp"},
    {"name": "Проклятье гоблинов", "image_url": "/static/cards/GoblinCurse.webp"},
    {"name": "Гоблин-подрывник", "image_url": "/static/cards/GoblinDemolisher.webp"},
    {"name": "Гоблинский бур", "image_url": "/static/cards/GoblinDrill.webp"},
    {"name": "Гоблинская машина", "image_url": "/static/cards/GoblinMachine.webp"},
    {"name": "Гоблинштейн", "image_url": "/static/cards/Goblinstein.webp"},
    {"name": "гоблины", "image_url": "/static/cards/Gobs.webp"},
    {"name": "Золотой рыцарь", "image_url": "/static/cards/GoldenKnight.webp"},
    {"name": "Голем", "image_url": "/static/cards/Golem.webp"},
    {"name": "Кладбище", "image_url": "/static/cards/Graveyard.webp"},
    {"name": "Стражи", "image_url": "/static/cards/Guards.webp"},
    {"name": "Дух исцеления", "image_url": "/static/cards/HealSpirit.webp"},
    {"name": "Орда миньонов", "image_url": "/static/cards/Horde.webp"},
    {"name": "Охотник", "image_url": "/static/cards/Hunter.webp"},
    {"name": "Ледяной голем", "image_url": "/static/cards/IceGolem.webp"},
    {"name": "Ледяной дух", "image_url": "/static/cards/IceSpirit.webp"},
    {"name": "Ледяной колжун", "image_url": "/static/cards/IceWiz.webp"},
    {"name": "Адская башня", "image_url": "/static/cards/Inferno.webp"},
    {"name": "Пламенный дракон", "image_url": "/static/cards/InfernoD.webp"},
    {"name": "Рыцарь", "image_url": "/static/cards/Knight.webp"},
    {"name": "Адская гончая", "image_url": "/static/cards/Lava.webp"},
    {"name": "Молния", "image_url": "/static/cards/Lightning.webp"},
    {"name": "Бревно", "image_url": "/static/cards/Log.webp"},
    {"name": "Дровосек", "image_url": "/static/cards/Lumber.webp"},
    {"name": "Магический лучник", "image_url": "/static/cards/MagicArcher.webp"},
    {"name": "Мегарыцарь", "image_url": "/static/cards/MegaKnight.webp"},
    {"name": "Шустрый шахтёр", "image_url": "/static/cards/MightyMiner.webp"},
    {"name": "Шахтёр", "image_url": "/static/cards/Miner.webp"},
    {"name": "Миньоны", "image_url": "/static/cards/Minions.webp"},
    {"name": "Зеркало", "image_url": "/static/cards/Mirror.webp"},
    {"name": "Мегаминьон", "image_url": "/static/cards/MM.webp"},
    {"name": "Монах", "image_url": "/static/cards/Monk.webp"},
    {"name": "Мортира", "image_url": "/static/cards/Mortar.webp"},
    {"name": "Ведьмина бабушка", "image_url": "/static/cards/MotherWitch.webp"},
    {"name": "мини-П.Е.К.К.А", "image_url": "/static/cards/MP.webp"},
    {"name": "Мушкетёр", "image_url": "/static/cards/Musk.webp"},
    {"name": "Ночная ведьма", "image_url": "/static/cards/NightWich.webp"},
    {"name": "Феникс", "image_url": "/static/cards/Phoenix.webp"},
    {"name": "Яд", "image_url": "/static/cards/Poison.webp"},
    {"name": "Принц", "image_url": "/static/cards/Prince.webp"},
    {"name": "Принцесса", "image_url": "/static/cards/Princess.webp"},
    {"name": "Сборщик элексира", "image_url": "/static/cards/Pump.webp"},
    {"name": "Ярость", "image_url": "/static/cards/Rage.webp"},
    {"name": "Таран", "image_url": "/static/cards/Ram.webp"},
    {"name": "Всадница на баране", "image_url": "/static/cards/RamRider.webp"},
    {"name": "Разбойники", "image_url": "/static/cards/Rascals.webp"},
    {"name": "Королевский гигант", "image_url": "/static/cards/RG.webp"},
    {"name": "Ракета", "image_url": "/static/cards/Rocket.webp"},
    {"name": "Королевская доставка", "image_url": "/static/cards/RoyalDelivery.webp"},
    {"name": "Королевские кабаны", "image_url": "/static/cards/RoyalHogs.webp"},
    {"name": "Королевские рекруты", "image_url": "/static/cards/RoyalRecruits.webp"},
    {"name": "Руническая гигантша", "image_url": "/static/cards/RuneGiant.webp"},
    {"name": "Армия скелетов", "image_url": "/static/cards/Skarmy.webp"},
    {"name": "Костяные драконы", "image_url": "/static/cards/SkeletonDragons.webp"},
    {"name": "Король скелетов", "image_url": "/static/cards/SkeletonKing.webp"},
    {"name": "Скелетики", "image_url": "/static/cards/Skellies.webp"},
    {"name": "Бочка со скелетами", "image_url": "/static/cards/SkellyBarrel.webp"},
    {"name": "Снежок", "image_url": "/static/cards/Snowball.webp"},
    {"name": "Спарки", "image_url": "/static/cards/Sparky.webp"},
    {"name": "Гоблины копейщики", "image_url": "/static/cards/SpearGobs.webp"},
    {"name": "Императрица духов", "image_url": "/static/cards/SpiritEmpress.webp"},
    {"name": "Подозрительный куст", "image_url": "/static/cards/SuspiciousBush.webp"},
    {"name": "Тесла", "image_url": "/static/cards/Tesla.webp"},
    {"name": "Надгробие", "image_url": "/static/cards/Tombstone.webp"},
    {"name": "Торнадо", "image_url": "/static/cards/Tornado.webp"},
    {"name": "Валькирия", "image_url": "/static/cards/Valk.webp"},
    {"name": "Лоза", "image_url": "/static/cards/Vines.webp"},
    {"name": "Бездна", "image_url": "/static/cards/Void.webp"},
    {"name": "Стенобои", "image_url": "/static/cards/WallBreakers.webp"},
    {"name": "Ведьма", "image_url": "/static/cards/Witch.webp"},
    {"name": "Колдун", "image_url": "/static/cards/Wiz.webp"},
    {"name": "Арбалет", "image_url": "/static/cards/XBow.webp"},
    {"name": "Разряд", "image_url": "/static/cards/Zap.webp"},
    {"name": "Мини-генераторы", "image_url": "/static/cards/Zappies.webp"},
    {"name": "Маленький принц", "image_url": "/static/cards/LittlePrince.webp"},
    {"name": "Стрелы", "image_url": "/static/cards/Arrows.webp"}

]